# Generated by Django 3.2.5 on 2022-12-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_dweet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dweet',
            options={'ordering': ['-created_at']},
        )
    ]
