# Generated by Django 4.1.4 on 2022-12-26 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_dweet_liked_dweet_updated_delete_dweetlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyp', models.CharField(max_length=300)),
                ('created_atp', models.DateTimeField(auto_now_add=True)),
                ('userp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posteds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
