# Generated by Django 4.1.4 on 2022-12-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='body',
            field=models.CharField(max_length=150),
        ),
    ]