# Generated by Django 4.1.4 on 2022-12-29 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_posted_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posted',
            name='likes',
        ),
        migrations.AddField(
            model_name='posted',
            name='likeds',
            field=models.ManyToManyField(blank=True, default=None, related_name='likeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posted',
            name='notreacts',
            field=models.ManyToManyField(blank=True, default=None, related_name='notreacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posted',
            name='unlikeds',
            field=models.ManyToManyField(blank=True, default=None, related_name='unlikeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posted',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='YurtUnlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('post_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YurtNotreact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('post_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YurtLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('post_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
