# Generated by Django 4.1.4 on 2022-12-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_posted_likes_posted_likeds_posted_notreacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yurtlike',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='YurtLike', max_length=10),
        ),
        migrations.AlterField(
            model_name='yurtnotreact',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='YurtNotreact', max_length=10),
        ),
        migrations.AlterField(
            model_name='yurtunlike',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Yurtunike', max_length=10),
        ),
    ]
